### ISSUE TITLE
Review and add hamburger menu coding

### ISSUE THREAD

**Issue by ElizabethWitengier** [jcrivlare/brewery-finder-app-crivlare-mccraw-pearsall-witengier#36]

**Comment by ElizabethWitengier** [comment]
Former Code (hamburger.js):

const nav = document.querySelector(".main_nav")
const hamburgerButton = document.querySelector(".navbar_toggle")

hamburgerButton.addEventListener("click", function(){
    nav.classList.toggle("show_nav")
})

**Comment by JPearsallUFL** [comment]
Question on where to attach the <script> for the hamburger menu
